#!/usr/bin/env node
/**
 * Generates the pixel arrow cursor as a PNG data URI.
 *
 * A native CSS cursor, not a DOM element tracking the pointer: the compositor
 * draws it, so it cannot lag behind the real pointer the way a JS-positioned
 * div does, it costs nothing per frame, and it yields correctly over native
 * UI. A lagging custom cursor is the commonest way this effect goes wrong.
 *
 * This replaced a rocket. The rocket was drawn nose-up and needed a 10 degree
 * lean, which had to be applied as a horizontal shear because rotating pixel
 * art this small tears it apart — a three-shear rotation, the trick that
 * normally rescues it, still pulled the nose off the hull. None of that
 * applies to an arrow: the standard pointer silhouette already carries its
 * own angle, drawn into the shape rather than applied to it, so there is no
 * transform here at all and nothing to degrade.
 *
 * Output is committed into global.css as a data URI, so there is no runtime
 * cost and no extra request. Re-run this only when the art changes.
 */
import sharp from 'sharp'
import { readFileSync, writeFileSync } from 'node:fs'

/* Two colours. The silhouette is the standard pointer, so the shape alone
   carries the "this is a cursor" reading and the fill is free to be the brand
   accent. The dark outline stays regardless — it is what keeps an orange
   pointer legible against the orange panels. */
const PALETTE = {
  '.': null,
  K: [10, 10, 12, 255], // outline — keeps it legible on any surface
  O: [235, 94, 40, 255], // --orange, the brand accent
}

/**
 * The classic arrow.
 *
 * Drawn at the canonical proportions: a point at the origin, a straight left
 * edge, a hypotenuse at roughly 45 degrees, the notch where the head meets
 * the tail, and a tail angled to the lower right. The left edge being exactly
 * vertical and the tip sitting exactly in the corner are what make it read as
 * a pointer rather than as a triangle — and they are what let the hotspot be
 * the true (0, 0) of the image.
 */
const ARROW = [
  'K........',
  'KK.......',
  'KOK......',
  'KOOK.....',
  'KOOOK....',
  'KOOOOK...',
  'KOOOOOK..',
  'KOOOOOOK.',
  'KOOOOKKKK',
  'KOOKOOK..',
  'KOKKOOK..',
  'KK..KOOK.',
  'K...KOOK.',
  '.....KK..',
]

const SCALE = 2

/** Paints the grid into a raw RGBA buffer at SCALE, one grid cell per block. */
function raster(grid) {
  const w = grid[0].length * SCALE
  const h = grid.length * SCALE
  const data = Buffer.alloc(w * h * 4)
  for (let y = 0; y < h; y += 1) {
    for (let x = 0; x < w; x += 1) {
      const px = PALETTE[grid[Math.floor(y / SCALE)][Math.floor(x / SCALE)]]
      if (!px) continue
      const i = (y * w + x) * 4
      data[i] = px[0]
      data[i + 1] = px[1]
      data[i + 2] = px[2]
      data[i + 3] = px[3]
    }
  }
  return { data, w, h }
}

const widths = new Set(ARROW.map((r) => r.length))
if (widths.size !== 1) throw new Error(`ragged grid, widths ${[...widths]}`)
for (const row of ARROW) {
  for (const ch of row) {
    if (!(ch in PALETTE)) throw new Error(`unknown palette char "${ch}"`)
  }
}
if (ARROW[0][0] !== 'K') throw new Error('the tip must sit in the top-left cell')

console.log(ARROW.map((r) => r.replace(/\./g, ' ')).join('\n'))

const { data, w, h } = raster(ARROW)
const png = await sharp(data, { raw: { width: w, height: h, channels: 4 } })
  .png({ compressionLevel: 9 })
  .toBuffer()

/* Hotspot at the tip, which the shape puts in the very first pixel — so this
   is the one cursor whose hotspot needs no arithmetic and cannot drift. */
const arrow = {
  uri: `data:image/png;base64,${png.toString('base64')}`,
  hotspot: [0, 0],
  size: [w, h],
  bytes: png.length,
}
console.log(`\n${arrow.size.join('x')}px  hotspot ${arrow.hotspot.join(',')}  ${png.length} bytes`)

writeFileSync('scripts/.cursor-data.json', JSON.stringify({ arrow }, null, 2))
console.log('wrote scripts/.cursor-data.json')

/* ---- inject into global.css between markers ---------------------------- */

const START = '/* cursor:start */'
const END = '/* cursor:end */'
const CSS_PATH = 'src/styles/global.css'

const block = `${START}
/* ===== Pixel arrow cursor =====
   Generated by scripts/build-cursor.mjs — edit the art there, not here.
   Inlined as a data URI so it costs no request and is painted by the
   compositor rather than chased by JavaScript.

   One cursor, no hover variant. Hover feedback is left to the colour and
   underline changes the interactive elements already carry.

   Interactive elements are listed explicitly even though they would inherit:
   the UA stylesheet sets its own \`cursor:pointer\` on links and buttons, and
   without a rule of their own they would flip back to the system arrow. The
   keyword after the var is the fallback if the data URI ever fails to
   decode, which is why it differs between the two rules.

   Gated on a fine pointer that can hover: touch has no cursor to replace,
   and overriding it there would do nothing but bloat the stylesheet.

   Tradeoff worth stating: a custom cursor ignores an enlarged system cursor
   set for accessibility. At ${arrow.size[0]}x${arrow.size[1]} this sits close to the default pointer
   size and carries a dark outline so it stays legible on any surface — but a
   user who needs a much larger pointer loses that here. */
@media (hover: hover) and (pointer: fine) {
  html { cursor: var(--cursor-arrow), auto; }
  a, button, [role="button"], summary,
  .mobile-tile, .project-card, .price-tier, canvas { cursor: var(--cursor-arrow), pointer; }
  input, textarea, select { cursor: text; }
  :disabled { cursor: not-allowed; }
}
${END}`

/* No trailing keyword here: each rule above supplies its own fallback. */
const vars = `  --cursor-arrow: url("${arrow.uri}") ${arrow.hotspot.join(' ')};`

let css = readFileSync(CSS_PATH, 'utf8')

/* Replace whatever cursor variable is currently there, whatever it is called.
   This has been --cursor-idle/--cursor-thrust and then --cursor-rocket; a
   chain of per-name migrations would only grow, so the rule is simply that
   this script owns every `--cursor-*` declaration in the file. */
const CURSOR_VAR = / {2}--cursor-[a-z-]+:[^\n]*\n/g
if (CURSOR_VAR.test(css)) {
  let first = true
  css = css.replace(CURSOR_VAR, () => {
    if (!first) return ''
    first = false
    return `${vars}\n`
  })
} else {
  css = css.replace(
    '  --orange-text:#F5854F;',
    `  --orange-text:#F5854F;\n\n  /* Arrow cursor, generated — see the block below. */\n${vars}`,
  )
}
css = css.replace(
  /\/\* [A-Za-z]+ cursors?, generated — see the block below\. \*\//,
  '/* Arrow cursor, generated — see the block below. */',
)

// Index-based splice rather than a RegExp: the markers contain / and * and
// the block contains base64, so escaping them into a pattern is a needless
// hazard. This also makes re-running strictly idempotent.
if (css.includes(START) && css.includes(END)) {
  const from = css.indexOf(START)
  const to = css.indexOf(END) + END.length
  css = css.slice(0, from) + block + css.slice(to)
} else {
  css = `${css.trimEnd()}

${block}
`
}

writeFileSync(CSS_PATH, css)
console.log(`injected cursor CSS into ${CSS_PATH}`)
