#!/usr/bin/env node
/**
 * Generates the pixel-rocket cursors as PNG data URIs.
 *
 * A native CSS cursor, not a DOM element tracking the pointer: the compositor
 * draws it, so it cannot lag behind the real pointer the way a JS-positioned
 * div does, it costs nothing per frame, and it yields correctly over native
 * UI. A lagging custom cursor is the commonest way this effect goes wrong.
 *
 * The art is authored nose-up and left that way. An earlier pass rotated it
 * 45 degrees to sit at an arrow-like angle; rotating pixel art this small
 * destroys it — rounding punches holes through the body and the silhouette
 * stops reading as a rocket at all. Pixel art is redrawn at an angle, never
 * rotated, and at 22px the upright form is the legible one.
 *
 * Output is committed into global.css as a data URI, so there is no runtime
 * cost and no extra request. Re-run this only when the art changes.
 */
import sharp from 'sharp'
import { writeFileSync } from 'node:fs'

const PALETTE = {
  '.': null,
  K: [10, 10, 12, 255], // outline — keeps it legible on any surface
  O: [235, 94, 40, 255], // --orange, the brand accent
  L: [245, 133, 79, 255], // --orange-text, the lit edge
  W: [255, 255, 255, 255], // window
  F: [255, 214, 138, 255], // flame
}

/** Shared hull. Flame rows are appended only for the active cursor. */
const HULL = [
  '.....K.....',
  '....KLK....',
  '....KLK....',
  '...KOLOK...',
  '...KOLOK...',
  '..KOOLOOK..',
  '..KOWWWOK..',
  '..KOWWWOK..',
  '..KOOLOOK..',
  '..KOOLOOK..',
  '.KOOOLOOOK.',
  'KOOKOLOKOOK',
  'KOK.KOK.KOK',
  '.K..KOK..K.',
]

const IDLE = [...HULL, '.....K.....']
const THRUST = [...HULL, '....KFK....', '....KFK....', '.....F.....']

const SCALE = 2

function toPng(grid) {
  const w = grid[0].length * SCALE
  const h = grid.length * SCALE
  const buf = Buffer.alloc(w * h * 4)
  for (let y = 0; y < h; y += 1) {
    for (let x = 0; x < w; x += 1) {
      const px = PALETTE[grid[Math.floor(y / SCALE)][Math.floor(x / SCALE)]]
      if (!px) continue
      const i = (y * w + x) * 4
      buf[i] = px[0]
      buf[i + 1] = px[1]
      buf[i + 2] = px[2]
      buf[i + 3] = px[3]
    }
  }
  return sharp(buf, { raw: { width: w, height: h, channels: 4 } }).png({ compressionLevel: 9 })
}

const results = {}
for (const [name, art] of [
  ['idle', IDLE],
  ['thrust', THRUST],
]) {
  const widths = new Set(art.map((r) => r.length))
  if (widths.size !== 1) throw new Error(`${name}: ragged grid, widths ${[...widths]}`)
  for (const row of art) {
    for (const ch of row) {
      if (!(ch in PALETTE)) throw new Error(`${name}: unknown palette char "${ch}"`)
    }
  }

  console.log(`\n--- ${name} ---`)
  console.log(art.map((r) => r.replace(/\./g, ' ')).join('\n'))

  const png = await toPng(art).toBuffer()
  /* Hotspot on the nose: column 5 of 11, top row. The click point is the tip
     of the rocket, the only place a user would expect it to be. */
  results[name] = {
    uri: `data:image/png;base64,${png.toString('base64')}`,
    hotspot: [5 * SCALE + 1, 0],
    size: [art[0].length * SCALE, art.length * SCALE],
    bytes: png.length,
  }
  console.log(
    `  ${results[name].size.join('x')}px  hotspot ${results[name].hotspot.join(',')}  ${png.length} bytes`,
  )
}

writeFileSync('scripts/.cursor-data.json', JSON.stringify(results, null, 2))
console.log('\nwrote scripts/.cursor-data.json')

/* ---- inject into global.css between markers ---------------------------- */
import { readFileSync } from 'node:fs'

const START = '/* cursor:start */'
const END = '/* cursor:end */'
const CSS_PATH = 'src/styles/global.css'

const block = `${START}
/* ===== Pixel rocket cursor =====
   Generated by scripts/build-cursor.mjs — edit the art there, not here.
   Inlined as a data URI so it costs no request and is painted by the
   compositor rather than chased by JavaScript.

   Gated on a fine pointer that can hover: touch has no cursor to replace,
   and overriding it there would do nothing but bloat the stylesheet.

   Tradeoff worth stating: a custom cursor ignores an enlarged system cursor
   set for accessibility. It is kept near the default size (22px) and carries
   a dark outline so it stays legible on any surface, but a user who needs a
   much larger pointer loses that here. */
@media (hover: hover) and (pointer: fine) {
  html { cursor: var(--cursor-idle); }
  a, button, [role="button"], summary,
  .mobile-tile, .project-card, .price-tier, canvas { cursor: var(--cursor-thrust); }
  input, textarea, select { cursor: text; }
  :disabled { cursor: not-allowed; }
}
${END}`

const vars = `  --cursor-idle: url("${results.idle.uri}") ${results.idle.hotspot.join(' ')}, auto;
  --cursor-thrust: url("${results.thrust.uri}") ${results.thrust.hotspot.join(' ')}, pointer;`

let css = readFileSync(CSS_PATH, 'utf8')

// Replace the variable pair, or add it inside :root on first run.
if (css.includes('--cursor-idle:')) {
  css = css.replace(/ {2}--cursor-idle:[^\n]*\n {2}--cursor-thrust:[^\n]*\n/, `${vars}\n`)
} else {
  css = css.replace(
    '  --orange-text:#F5854F;',
    `  --orange-text:#F5854F;\n\n  /* Rocket cursors, generated — see the block below. */\n${vars}`,
  )
}

// Index-based splice rather than a RegExp: the markers contain / and * and
// the block contains base64, so escaping them into a pattern is a needless
// hazard. This also makes re-running strictly idempotent.
if (css.includes(START) && css.includes(END)) {
  const from = css.indexOf(START)
  const to = css.indexOf(END) + END.length
  css = css.slice(0, from) + block + css.slice(to)
} else {
  css = `${css.trimEnd()}

${block}
`
}

writeFileSync(CSS_PATH, css)
console.log(`injected cursor CSS into ${CSS_PATH}`)
